### ISSUE TITLE
HPatches quantitative results

### ISSUE THREAD

**Issue by rlqud222** [dltan7/ECO-TR#3]
Hi,

Thanks for sharing your work and code!

Are you planning to release the codes for evaluation on the standard benchmarks you used for reporting in your paper?
If the evaluation codes are not going to be there, it would make the follow up works difficult to compare with your work. 
So hopefully the codes will be made available as I'm also enthusiastically waiting for it! 

Also, in the supplementary material, I found that you mentioned that the model enlarged the image x 1.5 times to obtain better results.
Doesn't this make an unfair comparison to existing works or maybe i misunderstood what you meant? 

Finally, COTR does not provide HPatches evaluation code as well, and I'm trying to reproduce the results but I'm kind of struggling at the point where "The final resulting dense correspondences area will be slightly smaller than the GT mask, because some corner/edge correspondences will be filtered out.".  If you could share how you reproduced the results for COTR, it would be amazing and extremely helpful for other researchers! 

Thanks!

**Comment by dltan7** [comment]
1. Yes. We'll release it later.
2. The input pair of each method are sharing the same original resolutions and ECO-TR resizes the input pair later. We think it is more like a kind of interpolation operation in the network.
3. We met the same problem during reproduction. Because this kind of method can not fill the edges by extrapolation right now. As a result, for both methods, we only took the areas which have predictions into account. These methods were evaluated under same code(modified from [DenseMathing](https://github.com/PruneTruong/DenseMatching)). You can drop me an email for the details.

**Comment by rlqud222** [comment]
Wait, i'm sorry. I'm a bit confused. For the second answer, do you mean you take an input pair of images (let's say it's 800x800) and then ECO-TR resizes the images to 1200x1200, processes them and outputs the flow at 1200x1200 and evaluate at 800x800?

**Comment by dltan7** [comment]
Yes. COTR does the same thing with its multi-stage zoom-ins. Generally, larger input size means better performance at the expense of more computation. ECO-TR is more efficient than COTR, which means we can resize the image only once and get comparable results.
